plugins {
    id 'com.android.library'
    id 'com.chaquo.python'
}

android {
    namespace = 'com.undcover.freedom.pyramid'
    compileSdk = 36

    defaultConfig {
        minSdkVersion = 24
        targetSdkVersion = 34
    }

    flavorDimensions = ["abi"]

    productFlavors {
        arm32 {
            dimension = "abi"
            ndk {
                abiFilters 'armeabi-v7a'
            }
        }

        arm64 {
            dimension = "abi"
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
        coreLibraryDesugaringEnabled = true
    }

    sourceSets {
        main {
            python.srcDirs = ["src/python"]
        }
    }
}

chaquopy {
    defaultConfig {
        version = "3.11"
        buildPython = ["py", "-3.11"]
        pip {
            install "lxml"
            install "pyquery"
            install "requests"
            install "jsonpath-ng"
            install "cachetools"
            install "pycryptodome"
            install "beautifulsoup4"
        }
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
}
